"""
Integration modules for external secret storage systems.
"""

import json
import sys
from typing import Dict, List, Optional

import boto3
import click
import hvac
import keyring
from botocore.exceptions import ClientError, NoCredentialsError


class AWSSecretsManager:
    """AWS Secrets Manager integration."""
    
    def __init__(self, region_name: str = 'us-east-1', profile_name: Optional[str] = None):
        try:
            # Create session with optional profile
            if profile_name:
                session = boto3.Session(profile_name=profile_name)
                self.client = session.client('secretsmanager', region_name=region_name)
            else:
                # Use default profile or environment variables
                self.client = boto3.client('secretsmanager', region_name=region_name)
        except NoCredentialsError:
            if profile_name:
                raise ValueError(f"AWS credentials not found for profile '{profile_name}'. Check your ~/.aws/credentials file.")
            else:
                raise ValueError("AWS credentials not found. Configure with 'aws configure' or set environment variables.")
        except Exception as e:
            if "could not be found" in str(e).lower():
                raise ValueError(f"AWS profile '{profile_name}' not found in ~/.aws/credentials")
            raise ValueError(f"AWS authentication error: {e}")
    
    def save_secret(self, secret_name: str, secret_value: str, description: str = "") -> bool:
        """Save a secret to AWS Secrets Manager."""
        try:
            # Try to create new secret
            self.client.create_secret(
                Name=secret_name,
                SecretString=secret_value,
                Description=description or f"Generated by Cryptex"
            )
            return True
        except ClientError as e:
            if e.response['Error']['Code'] == 'ResourceExistsException':
                # Secret exists, update it
                try:
                    self.client.update_secret(
                        SecretId=secret_name,
                        SecretString=secret_value,
                        Description=description or f"Updated by Cryptex"
                    )
                    return True
                except ClientError:
                    return False
            return False
    
    def save_multiple_secrets(self, secrets: Dict[str, str], prefix: str = "") -> Dict[str, bool]:
        """Save multiple secrets to AWS Secrets Manager."""
        results = {}
        for name, value in secrets.items():
            secret_name = f"{prefix}{name}" if prefix else name
            results[name] = self.save_secret(secret_name, value)
        return results


class HashiCorpVault:
    """HashiCorp Vault integration."""
    
    def __init__(self, url: str = 'http://localhost:8200', token: Optional[str] = None):
        self.client = hvac.Client(url=url, token=token)
        
        if not self.client.is_authenticated():
            raise ValueError("Vault authentication failed. Check your token and vault URL.")
    
    def save_secret(self, path: str, secret_value: str, mount_point: str = 'secret') -> bool:
        """Save a secret to HashiCorp Vault."""
        try:
            self.client.secrets.kv.v2.create_or_update_secret(
                path=path,
                secret={'value': secret_value},
                mount_point=mount_point
            )
            return True
        except Exception:
            return False
    
    def save_multiple_secrets(self, path: str, secrets: Dict[str, str], mount_point: str = 'secret') -> bool:
        """Save multiple secrets to HashiCorp Vault."""
        try:
            self.client.secrets.kv.v2.create_or_update_secret(
                path=path,
                secret=secrets,
                mount_point=mount_point
            )
            return True
        except Exception:
            return False


class OSKeychain:
    """OS-native keychain integration."""
    
    def __init__(self):
        pass
    
    def save_secret(self, service: str, username: str, password: str) -> bool:
        """Save a secret to OS keychain."""
        try:
            keyring.set_password(service, username, password)
            return True
        except Exception:
            return False
    
    def save_multiple_secrets(self, service: str, secrets: Dict[str, str]) -> Dict[str, bool]:
        """Save multiple secrets to OS keychain."""
        results = {}
        for name, value in secrets.items():
            results[name] = self.save_secret(service, name, value)
        return results


def check_integration_dependencies() -> Dict[str, bool]:
    """Check which integrations are available."""
    return {
        'aws': True,
        'vault': True,
        'keyring': True,
    }